const fr =
 
{
	"home": "Accueil",
	"logout": "Déconnexion",
	"email": "Adresse E-Mail",
	"password": "Mot de passe",
	"login": "Connexion",
	"select_log_file_location": "Sélectionnez l’emplacement du fichier Journal de Combat :",
	"choose_button": "Choisir...",
	"upload_button": "Télécharger un journal",
	"livelog_button": "Journal direct",
	"splitlog_button": "Diviser un journal",
	"upload_desc": "Vous avez déjà terminé de raid et vous voulez télécharger le fichier de log pour ce raid.",
	"livelog_desc": "Vous êtes sur le point de lancer le raid et voulez enregistrer le log en temps réel.",
	"splitlog_desc": "Vous souhaitez fractionner un fichier de log qui contient plusieurs raids sans les télécharger.",
	"choose_file_for_upload": "Choisissez le fichier que vous voulez télécharger :",
	"choose_file_for_split": "Choisissez le fichier que vous voulez fractionner :",
	"choose_livelog_directory": "Choisissez le répertoire des logs de l'installation de votre jeu :",
	"choose_livelog_file": "Choisissez le fichier de log à surveiller :",
	"choose_guild": "Choisissez la guilde que vous pour laquelle vous souhaitez télécharger :",
	"public_report": "Public",
	"private_report": "Privé",
	"unlisted_report": "Non listé",
	"description_report_label": "Entrez une description pour le rapport :",
	"select_specific_raids": "Sélectionner les raids spécifiques que vous souhaitez télécharger",
	"go_button": "C'est parti !",
	"choose_guild_or_personal_logs": "Choisissez une guilde ou vos journaux personnels en cliquant sur une des cases ci-dessous :",
	"ok_button": "Ok",
	"cancel_button": "Annuler",
	"choose_language": "Choisissez votre langue préférée en cliquant sur l'une des cases ci-dessous :",
	"choose_version": "Choisissez votre version préférée du jeu en cliquant sur l'une des cases ci-dessous :",
	"processing_log_file": "Traitement du fichier de log",
	"uploading_fights": "Téléchargement des combats",
	"downloading_update": "Mise à jour des téléchargements",
	"click_go_home": "Cliquer sur le bouton Accueil en haut à gauche pour revenir à la première page.",
	"view_report_desc": "Vous pouvez voir votre rapport sur le site en cliquant sur le bouton Voir rapport ci-dessous.",
	"view_report_button": "Voir rapport",
	"view_report_in_game_button": "Afficher le rapport dans le jeu",
	"view_report_in_browser_button": "Afficher le rapport dans le navigateur",
	"delete_or_archive_desc": "Vous pouvez supprimer ou archiver un fichier de log. La suppression va détruire le fichier de log, et l'archivage va le mettre dans un sous-dossier dans le répertoire des fichiers de log.",
	"delete_log_button": "Supprimer un fichier de log",
	"archive_log_button": "Archiver un fichier de log",
	"done_button": "Terminé",
	"fight_details": "Survolez les noms des ennemis dans la liste à gauche pour voir les détails sur les combats dans cette zone.",
	"include_trash_fights": "Inclure les 'Trash' combats",
	"error_label": "Erreur :",
	"warning_label": "Alerte :",
	"lost_connection": "Connexion perdue. Quittez l'application et connectez-vous à nouveau.",
	"missing_user_or_password": "Vous devez renseigner un nom d'utilisateur et un mot de passe.",
	"login_error": "Une erreur s'est produite, essayez de vous reconnecter !",
	"empty_response_error": "Le serveur a envoyé une réponse vide. La connexion a du échouer.",
	"livelog_started": "Rapport créé. L'enregistrement en live a commencé.",
	"upload_chunk_success": "Téléchargement de nouveaux joueurs, PNJ et familiers réussi.",
	"upload_error": "Impossible de télécharger.",
	"waiting_for_data": "Données téléchargées avec succès. En attente de données supplémentaires.",
	"reading_log_file": "Lecture du log",
	"splitting_log_file": "Séparation du log",
	"scanning_log_file": "Scanne des logs pour les raids",
	"uploading_new_fights": "Téléchargement de nouveaux combats",
	"uploading_new_actors": "Téléchargement de nouveaux joueurs, PNJ et familiers",
	"waiting_for_fight_end": "Données traitées. En attente de la fin de combat avant téléchargement.",
	"processed_new_fights": "Traitement des nouveaux combats.",
	"compressing_data": "Compression des données du log du combat",
	"no_file_selected_error": "Vous devez renseigner un fichier.",
	"invalid_file_selected_error": "Fichier sélectionné invalide.",
	"file_too_large_error": "Ce fichier fait plus de 1,5 gigaoctets. Divisez le fichier journal et téléchargez les pièces séparément. Vous pouvez le faire en cliquant sur «Accueil», puis sur «Fractionner un journal».",
	"file_too_many_days_error": "Ce log contient plus d'un jour de données. Vous devriez séparer le fichier avant de le télécharger ou de sélectionner les combats à télécharger.",
	"no_region_selected_error": "Pour des journaux personnels, vous devez spécifier la région de téléchargement. Cliquer sur le bouton <i>Choisir...</i> ci-dessous et sélectionner une région.",
	"cleanup_success": "Nettoyage réussi.",
	"cleaning_up": "Nettoyage en cours...",
	"uploading_remaining": "Téléchargement des données restantes avant de clore la session...",
	"assuming_combat_over": "En supposant que le combat est terminé. Compression des logs du combat",
	"reading_new_log_data": "Lecture du nouveau fichier de log",
	"no_livelog_location_error": "Vous devez spécifier un emplacement.",
	"invalid_livelog_location_error": "Emplacement sélectionné incorrect.",
	"confirm_deletion": "Êtes-vous sûr de vous supprimer ce fichier ?",
	"yes": "Oui",
	"no": "Non",
	"deletion_failed": "Échec de la suppression. Fermer les autres applications et réessayer.",
	"deletion_success": "Le fichier a été supprimé avec succès.",
	"confirm_archival": "Êtes-vous sûr de vouloir archiver ce fichier ?",
	"archival_success": "Le fichier a été archivé avec succès.",
	"archival_failure": "Échec de l'archivage. Fermer les autres applications et réessayer.",
	"no_fight_selected": "Vous devez sélectionner au moins un combat à télécharger.",
	"date_label": "Date:",
	"duration_label": "Durée:",
	"friendlies_label": "Participants amicaux:",
	"enemies_label": "Participants ennemis:",
	"wipe": "Mourir",
	"kill": "Tuer",
	"start_recording_button": "Commencer l'enregistrement",
	"no_directory_error": "Vous devez spécifier un fichier.",
	"invalid_directory_error": "Le fichier sélectionné est invalide.",
	"stop_recording_button": "Arrêter l'enregistrement",
	"stop_button": "\nArrêtez",
	"delete_button": "Effacer",
	"archive_button": "Archive",
	"ff_act_warning": "La version de ACT 2.0.2.9 est requise au minimum pour enregistrer un log.",
	"warcraft_difficulty_mythic": "Mythique",
	"warcraft_difficulty_heroic": "Héroïque",
	"warcraft_difficulty_flex": "Flexible",
	"warcraft_difficulty_normal": "Normal",
	"warcraft_difficulty_lfr": "LFR",
	"warcraft_difficulty_challenge_mode": "Mode défi",
	"warcraft_difficulty_mythic_plus": "Mythique+",
	"live_version": "Dragonflight",
	"classic_version": "Classique",
	"test_version": "PTR",
	"forgot_password": "Mot de passe perdu ?",
	"create_account": "Créer un compte",
	"release_notes": "Notes de Patch",
	"characters": "Personnages",
	"guilds": "Guildes",
	"reports": "Rapports",
	"reports_viewer": "\nVisionneuse de rapports",
	"character_viewer": "\nVisionneuse de caractères",
	"guild_viewer": "\nVisionneuse de guildes",
	"rankings": "Classements",
	"gear": "Equipement",
	"character_viewer_desc1": "\nCe volet affiche des informations sur les caractères. Vous pouvez charger un caractère en utilisant l'une des méthodes suivantes:",
	"character_viewer_desc2": "Renseigner un nom de personnage dans le champ de recherche ci-dessus.",
	"character_viewer_desc3": "Sélectionnez l'un de vos personnages dans la barre latérale <i> Mes guildes </i>.",
	"character_viewer_desc4": "Cliquez sur le nom d'un personnage dans la barre latérale <i> Caractères récents </i>.",
	"raids": "Raids",
	"mythic_plus_dungeons": "Donjons mythiques +",
	"my_characters": "\nMes personnages",
	"my_guilds": "\nMes guildes",
	"recent_characters": "Personnages récents",
	"group_applicants": "Candidats de groupe",
	"recent_reports": "Rapports récents",
	"edit": "\nÉditer",
	"show_hide_overlay": "Afficher / masquer la superposition:",
	"call_wipe": "Demander un Wype: ",
	"call_wipe_help": "Utiliser la touche <em>Demander un Wype</em> pendant un journal direct vous permet de télécharger uniquement les données enregistrées avant l'appel du Wype.",
	"calling_wipe": "Demande de Wype en cours...",
	"wipe_called": "Wype annoncé.",
	"failed_to_call_wipe": "Échec de l'appel au Wype.",
	"can_only_call_a_wipe_when_live_logging": "\nVous ne pouvez appeler un effacement que si vous enregistrez en direct.\n",
	"guild_viewer_desc1": "\nCe volet affiche des informations sur les guildes. Vous pouvez charger une guilde en utilisant l'une des méthodes suivantes:",
	"guild_viewer_desc2": "\nTapez un nom de guilde dans le champ de recherche ci-dessus.",
	"guild_viewer_desc3": "\nSélectionnez l'une de vos guildes dans la barre latérale <i> Mes guildes </i>.",
	"operation_in_progress": "\nUne opération est déjà en cours et doit se terminer avant de pouvoir continuer.",
	"character_lookup_uses_preferred_region": "\nLa recherche de personnage utilise votre région préférée."
}
 
module.exports = { fr }