const br =
 
{
	"home": "Página Inicial",
	"logout": "Logout",
	"email": "Endereço de E-Mail",
	"password": "Senha",
	"login": "Login",
	"select_log_file_location": "Escolha um Local Para o Arquivo de Log de Combate:",
	"choose_button": "Escolha...",
	"upload_button": "Fazer Upload de um Log",
	"livelog_button": "Log Ao Vivo",
	"splitlog_button": "Dividir um Log",
	"upload_desc": "Você já terminou a raid e quer fazer upload do arquivo de log dela.",
	"livelog_desc": "Você está prestes a começar a raid e quer logá-la em tempo real.",
	"splitlog_desc": "Você quer dividir um arquivo de log que contém várias raids sem fazer o upload.",
	"choose_file_for_upload": "Escolha o arquivo que quer fazer upload:",
	"choose_file_for_split": "Escolha o arquivo que quer dividir:",
	"choose_livelog_directory": "Escolha o diretório de logs da sua instalação do jogo:",
	"choose_livelog_file": "Escolha o arquivo de log a ser monitorado:",
	"choose_guild": "Escolha a guilda para a qual quer fazer upload:",
	"public_report": "Público",
	"private_report": "Privado",
	"unlisted_report": "Não Listado",
	"description_report_label": "Insira uma descrição para o relatório:",
	"select_specific_raids": "Selecione Raids Específicas Para Upload",
	"go_button": "Pronto!",
	"choose_guild_or_personal_logs": "Escolha uma guilda ou seus logs pessoais clicando em uma das caixas abaixo:",
	"ok_button": "Ok",
	"cancel_button": "Cancelar",
	"choose_language": "Escolha seu idioma preferido clicando em uma das caixas abaixo:",
	"choose_version": "Escolha a versão do seu jogo preferido clicando em uma das caixas abaixo:",
	"processing_log_file": "Processando Arquivo de Log",
	"uploading_fights": "Fazendo Upload de Batalhas",
	"downloading_update": "Baixando Atualização",
	"click_go_home": "Clique no botão Página Inicial na parte superior esquerda para retornar à página inicial.",
	"view_report_desc": "Você pode ver seu relatório no site clicando o botão Ver Relatório abaixo.",
	"view_report_button": "Ver Relatório",
	"view_report_in_game_button": "Ver Relatório em Jogo",
	"view_report_in_browser_button": "Ver Relatório no Navegador",
	"delete_or_archive_desc": "Você pode excluir ou arquivar o log. Exclusão vai apagar o log, e arquivamento vai colocá-lo numa subpasta no diretório do arquivo do log.",
	"delete_log_button": "Deletar Log",
	"archive_log_button": "Arquivar Log",
	"done_button": "Pronto",
	"fight_details": "Passe o mouse sobre o nome dos inimigos na lista à esquerda para ver detalhes das batalhas nesta caixa.",
	"include_trash_fights": "Incluir Batalhas Com Inimigos Comuns",
	"error_label": "Erro:",
	"warning_label": "Aviso:",
	"lost_connection": "Conexão perdida. Feche o app e faça login novamente.",
	"missing_user_or_password": "Você deve especificar tanto um nome de usuário como uma senha.",
	"login_error": "Erro ao tentar logar!",
	"empty_response_error": "O servidor enviou uma resposta vazia. O login deve ter falhado de alguma forma.",
	"livelog_started": "Relatório criado. Log ao vivo iniciado.",
	"upload_chunk_success": "O upload de novos jogadores, NPCs e mascotes foi feito com sucesso.",
	"upload_error": "Falha no upload.",
	"waiting_for_data": "Dados submetidos com sucesso. Aguardando mais dados.",
	"reading_log_file": "Lendo Log de Combate",
	"splitting_log_file": "Dividindo Log de Combate",
	"scanning_log_file": "Procurando Raids no Log de Combate",
	"uploading_new_fights": "Fazendo Uploads de Novas Batalhas",
	"uploading_new_actors": "Fazendo Upload de Novos Jogadores, NPCs e Mascotes",
	"waiting_for_fight_end": "Dados processados. Aguardando logar o fim da batalha antes de fazer o upload.",
	"processed_new_fights": "Novas Batalhas Processadas.",
	"compressing_data": "Comprimindo Dados do Log De Combate",
	"no_file_selected_error": "Você deve especificar um arquivo.",
	"invalid_file_selected_error": "Arquivo inválido selecionado.",
	"file_too_large_error": "Este arquivo tem mais de 1.5 gigabytes. Divida o arquivo de registro e faça o upload das partes separadamente. Você pode fazer isso clicando em \"Inicio\" e então em \"Dividir Registro\".",
	"file_too_many_days_error": "Este arquivo de log contém mais de um dia de dados. Você deve ou dividi-lo antes de fazer o upload ou selecionar batalhas específicas para fazer o upload.",
	"no_region_selected_error": "Para logs pessoais, você deve especificar a região para a qual está fazendo upload. Aperte o botão <i>Escolher...</i> acima e escolha uma região.",
	"cleanup_success": "Limpeza Bem-Sucedida.",
	"cleaning_up": "Limpando...",
	"uploading_remaining": "Fazendo upload dos dados restantes antes de terminar a sessão...",
	"assuming_combat_over": "Presumindo que o combate terminou. Comprimindo Dados do Log de Combate",
	"reading_new_log_data": "Lendo Novos Dados do Log de Combate",
	"no_livelog_location_error": "Você deve especificar um local para o log ao vivo.",
	"invalid_livelog_location_error": "Local de log inválido selcionado.",
	"confirm_deletion": "Você tem certeza que quer excluir este arquivo?",
	"yes": "Sim",
	"no": "Não",
	"deletion_failed": "Exclusão falhou. Feche outros aplicativos e tente novamente.",
	"deletion_success": "O arquivo foi excluído com êxito.",
	"confirm_archival": "Você tem certeza que quer arquivar este arquivo?",
	"archival_success": "O arquivo foi arquivado com êxito.",
	"archival_failure": "Arquivamento falhou. Feche outros aplicativos e tente novamente.",
	"no_fight_selected": "Você deve selecionar ao menos uma batalha para fazer o upload.",
	"date_label": "Data:",
	"duration_label": "Duração:",
	"friendlies_label": "Participantes Amigáveis:",
	"enemies_label": "Participantes Inimigos:",
	"wipe": "Derrota",
	"kill": "Abate",
	"start_recording_button": "Iniciar Gravação",
	"no_directory_error": "Você deve especificar um diretório.",
	"invalid_directory_error": "Diretório inválido selecionado.",
	"stop_recording_button": "Parar Gravação",
	"stop_button": "Parar",
	"delete_button": "Excluir",
	"archive_button": "Arquivar",
	"ff_act_warning": "Versão 2.0.2.9 ou mais recente do plugin ACT necessária para os uploads de log do Shadowbringers.",
	"warcraft_difficulty_mythic": "Mítico",
	"warcraft_difficulty_heroic": "Heróico",
	"warcraft_difficulty_flex": "Flex",
	"warcraft_difficulty_normal": "Normal",
	"warcraft_difficulty_lfr": "LFR",
	"warcraft_difficulty_challenge_mode": "CM",
	"warcraft_difficulty_mythic_plus": "Mítico+",
	"live_version": "Terras Sombrias",
	"classic_version": "Clássica",
	"test_version": "RTP",
	"forgot_password": "Esqueceu a senha?",
	"create_account": "Criar Conta",
	"release_notes": "Notas de atulização",
	"characters": "Personagens",
	"guilds": "Guildas",
	"reports": "Relatórios",
	"reports_viewer": "Visualizar Relatórios ",
	"character_viewer": "Visualizar Personagens",
	"guild_viewer": "Visualizar Guildas",
	"rankings": "Classificações",
	"gear": "Equipamento",
	"character_viewer_desc1": "Este painel mostra informações sobre personagens. Você pode carregar um personagem usando qualquer um dos seguintes métodos: ",
	"character_viewer_desc2": "Type a character name into the search field above.",
	"character_viewer_desc3": "Select one of your characters from the <i>My Guilds</i> sidebar.",
	"character_viewer_desc4": "Click a character name from the <i>Recent Characters</i> sidebar.",
	"raids": "Raids",
	"mythic_plus_dungeons": "Mythic+ Dungeons",
	"my_characters": "Meus Personagens ",
	"my_guilds": "Minha Guilda",
	"recent_characters": "Personagens Recentes",
	"group_applicants": "Group Applicants",
	"recent_reports": "Relatórios Recentes",
	"edit": "Editar",
	"show_hide_overlay": "Show/Hide Overlay: ",
	"call_wipe": "Call a Wipe: ",
	"call_wipe_help": "Pressing the <em>Call a Wipe</em> hotkey while live-logging will allow you to filter the uploaded fight to only the data that was recorded before a wipe was called.",
	"calling_wipe": "Calling a wipe...",
	"wipe_called": "A wipe has been called.",
	"failed_to_call_wipe": "Failed to call a wipe.",
	"can_only_call_a_wipe_when_live_logging": "You can only call a wipe if you are live logging.",
	"guild_viewer_desc1": "This pane shows information about guilds. You can load a guild using any of the following methods:",
	"guild_viewer_desc2": "Type a guild name into the search field above.",
	"guild_viewer_desc3": "Select one of your guilds from the <i>My Guilds</i> sidebar.",
	"operation_in_progress": "An operation is already in progress and must complete before you can continue.",
	"character_lookup_uses_preferred_region": "Character lookup uses your preferred region."
}
 
module.exports = { br }