const ja =
 
{
	"home": "ホーム",
	"logout": "ログアウト",
	"email": "メールアドレス",
	"password": "パスワード",
	"login": "ログイン",
	"select_log_file_location": "ログ ファイルの場所を選択します:",
	"choose_button": "選択...",
	"upload_button": "アップロード",
	"livelog_button": "ライブログ",
	"splitlog_button": "ログの分割",
	"upload_desc": "終了したレイドのログをアップロードします。",
	"livelog_desc": "リアルタイムでレイドのログをアップロードします。",
	"splitlog_desc": "アップロードせずに複数の戦闘を記録したファイルを分割します。",
	"choose_file_for_upload": "アップロードするファイルの選択:",
	"choose_file_for_split": "分割するファイルの選択:",
	"choose_livelog_directory": "ゲームインストールのlogsフォルダを選択してください:",
	"choose_livelog_file": "ライブログするファイルの選択:",
	"choose_guild": "アップロードしたいギルドと地域を選択してください:",
	"public_report": "公開",
	"private_report": "非公開",
	"unlisted_report": "限定公開",
	"description_report_label": "レポートの説明を入力してください:",
	"select_specific_raids": "エリアを選択してアップロード",
	"go_button": "開始！",
	"choose_guild_or_personal_logs": "アップロードしたいギルドまたは、個人ログを選択してください:",
	"ok_button": "選択",
	"cancel_button": "キャンセル",
	"choose_language": "下のボックスのいずれかをクリックして、ご希望の言語を選択してください:",
	"choose_version": "下のボックスのいずれかをクリックして、ご希望のゲームバージョンを選択してください:",
	"processing_log_file": "処理ログファイル",
	"uploading_fights": "戦闘のアップロード",
	"downloading_update": "アップデートのダウンロード",
	"click_go_home": "最初のページに戻るには、左上の「ホーム」をクリックしてください。",
	"view_report_desc": "レポート表示をクリックすることで、ウェブサイトでレポートを確認することが出来ます。",
	"view_report_button": "レポート表示",
	"view_report_in_game_button": "ゲームでレポートを見る",
	"view_report_in_browser_button": "ブラウザでレポートを見る",
	"delete_or_archive_desc": "アップロードしたログファイルを削除または、アーカイブすることが出来ます。 「Delete...」をクリックするとログファイルが削除されます。「Archive...」をクリックするとサブフォルダーに保存されます。",
	"delete_log_button": "ログファイルの削除",
	"archive_log_button": "ログファイルの保存",
	"done_button": "完了",
	"fight_details": "敵の名前にカーソルを合わせると戦闘の詳細が確認できます。",
	"include_trash_fights": "ボス以外の戦闘を含む",
	"error_label": "エラー:",
	"warning_label": "警告:",
	"lost_connection": "接続が切れました。アプリを終了して再度ログインします。",
	"missing_user_or_password": "ユーザー名とパスワードの両方を指定する必要があります。",
	"login_error": "ログインしようとしてエラーが発生しました。",
	"empty_response_error": "サーバーが応答しません。ログインに失敗しました。",
	"livelog_started": "レポートが作成されました。 ライブロギングが開始されました。",
	"upload_chunk_success": "新規プレイヤー、NPC、ペットのアップロードに成功しました。",
	"upload_error": "アップロードに失敗しました。",
	"waiting_for_data": "データがアップロードされました。 更にデータを待っています。",
	"reading_log_file": "戦闘ログの読み込み",
	"splitting_log_file": "戦闘ログの分割",
	"scanning_log_file": "レイドの戦闘記録をスキャン",
	"uploading_new_fights": "新しい戦闘のアップロード",
	"uploading_new_actors": "新規プレイヤー、NPC、ペットのアップロード",
	"waiting_for_fight_end": "データ処理済み。アップロードする前に戦闘の終了が記録されるのを待っています。",
	"processed_new_fights": "新しい戦闘を処理しました。",
	"compressing_data": "戦闘ログデータの圧縮",
	"no_file_selected_error": "ファイルを指定する必要があります。",
	"invalid_file_selected_error": "無効なファイルが選択されました。",
	"file_too_large_error": "このファイルは1.5ギガバイトを超えています。ログファイルを分割して、別々にアップロードしてください。これは、「ホーム」、「ログの分割」の順にクリックすることで行うことができます。",
	"file_too_many_days_error": "このログファイルには、1日以上のデータが含まれています。 アップロードする前に分割するか、アップロードする特定の戦闘を選択する必要があります。",
	"no_region_selected_error": "個人ログの場合は、アップロード先の地域を指定する必要があります。上の<i>選択... </i>ボタンを押して地域を選択してください。",
	"cleanup_success": "クリーンアップ成功",
	"cleaning_up": "クリーニングアップ...",
	"uploading_remaining": "セッションを終了する前に残りのデータをアップロードしています...",
	"assuming_combat_over": "戦闘が終了したと仮定します。戦闘ログデータの圧縮",
	"reading_new_log_data": "新しい戦闘ログデータの読み込む",
	"no_livelog_location_error": "ライブログの場所を指定する必要があります。",
	"invalid_livelog_location_error": "無効なログの場所が選択されました。",
	"confirm_deletion": "このファイルを削除してよろしいですか？",
	"yes": "はい",
	"no": "いいえ",
	"deletion_failed": "削除に失敗しました。他のアプリケーションを閉じてやり直してください。",
	"deletion_success": "ファイルは正常に削除されました。",
	"confirm_archival": "このファイルをアーカイブしますか？",
	"archival_success": "ファイルは正常にアーカイブされました。",
	"archival_failure": "アーカイブは失敗しました。他のアプリケーションを閉じてやり直してください。",
	"no_fight_selected": "アップロードする戦闘を少なくとも1つ選択する必要があります。",
	"date_label": "日付:",
	"duration_label": "戦闘時間:",
	"friendlies_label": "フレンドリーな参加者:",
	"enemies_label": "敵の参加者:",
	"wipe": "全滅",
	"kill": "討伐",
	"start_recording_button": "記録開始",
	"no_directory_error": "ファイルを指定する必要があります。",
	"invalid_directory_error": "無効なファイルが選択されました。",
	"stop_recording_button": "記録停止",
	"stop_button": "停止",
	"delete_button": "削除",
	"archive_button": "アーカイブ",
	"ff_act_warning": "「ファイナルファンタジーXIV: 漆黒のヴィランズ」のログをアップロードするには、FFXIV ACT Plugin バージョン2.0.2.9 以上が必要になります。",
	"warcraft_difficulty_mythic": "神話",
	"warcraft_difficulty_heroic": "英雄",
	"warcraft_difficulty_flex": "Flex",
	"warcraft_difficulty_normal": "ノーマル",
	"warcraft_difficulty_lfr": "LFR",
	"warcraft_difficulty_challenge_mode": "CM",
	"warcraft_difficulty_mythic_plus": "神話+",
	"live_version": "シャドウランズ",
	"classic_version": "クラシック",
	"test_version": "PTR",
	"forgot_password": "パスワードをお忘れですか？",
	"create_account": "アカウントの作成",
	"release_notes": "リリースノート",
	"characters": "キャラクター",
	"guilds": "ギルド",
	"reports": "レポート",
	"reports_viewer": "レポートビューア",
	"character_viewer": "キャラクタービューア",
	"guild_viewer": "ギルドビューア",
	"rankings": "ランキング",
	"gear": "装備",
	"character_viewer_desc1": "このペインには、キャラクターに関する情報が表示されます。以下のいずれかの方法でキャラクターを読み込むことができます:",
	"character_viewer_desc2": "上記の検索欄にキャラクター名を入力してください。",
	"character_viewer_desc3": "<i>マイギルド</i>サイドバーからキャラクターを1人選択してください。",
	"character_viewer_desc4": "<i>最近のキャラクター</i>サイドバーからキャラクター名をクリックします。",
	"raids": "レイド",
	"mythic_plus_dungeons": "ミシック+ ダンジョン",
	"my_characters": "マイキャラクター",
	"my_guilds": "マイギルド",
	"recent_characters": "最近のキャラクター",
	"group_applicants": "グループ申請者",
	"recent_reports": "最近のレポート",
	"edit": "編集",
	"show_hide_overlay": "オーバーレイの表示/非表示: ",
	"call_wipe": "全滅を呼び出す: ",
	"call_wipe_help": "ライブロギング中に <em>全滅を呼び出す</em> のホットキーを押すと、呼び出す前に記録されたデータのみにアップロードをフィルタリングできます。",
	"calling_wipe": "全滅を呼び出しています...",
	"wipe_called": "全滅が呼び出されました。",
	"failed_to_call_wipe": "全滅を呼び出せませんでした。",
	"can_only_call_a_wipe_when_live_logging": "ライブロギングを行っている場合のみ、全滅を呼び出すことができます。",
	"guild_viewer_desc1": "このペインにはギルドに関する情報が表示されます。以下のいずれかの方法でギルドを読み込むことができます:",
	"guild_viewer_desc2": "上記の検索欄にギルド名を入力してください。",
	"guild_viewer_desc3": "<i>マイギルド</i>サイドバーからギルドを選択してください。",
	"operation_in_progress": "操作はすでに進行中です。続行する前に操作を完了する必要があります。",
	"character_lookup_uses_preferred_region": "文字検索では、ご希望の地域が使用されます。"
}
 
module.exports = { ja }