const ru =
 
{
	"home": "Главная",
	"logout": "Выйти",
	"email": "Адрес почты",
	"password": "Пароль",
	"login": "Войти",
	"select_log_file_location": "Выберите директорию с файлом лога:",
	"choose_button": "Выбрать...",
	"upload_button": "Отправить лог",
	"livelog_button": "Транслировать лог",
	"splitlog_button": "Разделить лог",
	"upload_desc": "Вы завершили рейд и хотите загрузить лог на сайт.",
	"livelog_desc": "Вы собираетесь начать рейд и хотите транслировать лог в реальном времени.",
	"splitlog_desc": "Вы хотите разделить лог, который содержит несколько рейдов, на отдельные файлы.",
	"choose_file_for_upload": "Выберите файл, который необходимо загрузить:",
	"choose_file_for_split": "Выберите файл, который необходимо разделить:",
	"choose_livelog_directory": "Выберите директорию логов в папке игры:",
	"choose_livelog_file": "Выберите лог для мониторинга:",
	"choose_guild": "Выберите гильдию, для которой будет загружен лог:",
	"public_report": "Открытые",
	"private_report": "Скрытые",
	"unlisted_report": "Частные",
	"description_report_label": "Введите описание отчета:",
	"select_specific_raids": "Выберите конкретные рейды для отправки",
	"go_button": "Поехали!",
	"choose_guild_or_personal_logs": "Выберите гильдию или Ваш персональный лог, нажав на одно из полей ниже:",
	"ok_button": "Ок",
	"cancel_button": "Отмена",
	"choose_language": "Выберите предпочитаемый язык, нажав на одно из полей ниже:",
	"choose_version": "Выберите предпочитаемую версию, нажав на одно из полей ниже:",
	"processing_log_file": "Обработка лога",
	"uploading_fights": "Отправка сражений",
	"downloading_update": "Скачивание обновления",
	"click_go_home": "Нажмите на кнопку \"Главная\" вверху слева, чтобы вернуться на стартовую страницу.",
	"view_report_desc": "Вы можете посмотреть свой отчет на сайте, нажав на кнопку \"Посмотреть отчет\" ниже.",
	"view_report_button": "Посмотреть отчет",
	"view_report_in_game_button": "Посмотреть отчет в игре",
	"view_report_in_browser_button": "Посмотреть отчет в браузере",
	"delete_or_archive_desc": "Вы можете удалить или архивировать файл лога. Удаление поможет избавиться от файла полностью, а архивирование поместит его в папку в соответствующей директории.",
	"delete_log_button": "Удалить файл лога",
	"archive_log_button": "Архивировать файл лога",
	"done_button": "Done",
	"fight_details": "Наведите указатель мыши на имена врагов в списке слева, чтобы увидеть подробности о сражениях в этом поле.",
	"include_trash_fights": "Включить сражения с обычными противниками",
	"error_label": "Ошибка:",
	"warning_label": "Предупреждение:",
	"lost_connection": "Соединение потеряно. Перезапустите приложение.",
	"missing_user_or_password": "Вы должны ввести логин и пароль.",
	"login_error": "При попытке входа произошла ошибка!",
	"empty_response_error": "Сервер не смог обработать запрос. Попытка входа не удалась.",
	"livelog_started": "Отчет создан. Транслирование лога включено.",
	"upload_chunk_success": "Отправка новых игроков, НИПов и питомцев прошла успешно.",
	"upload_error": "Ошибка при отправке.",
	"waiting_for_data": "Данные успешно отправлены. Ожидание новых данных.",
	"reading_log_file": "Чтение файла лога",
	"splitting_log_file": "Разделение файла лога",
	"scanning_log_file": "Поиск рейдов в файле логов",
	"uploading_new_fights": "Отправка новых сражений",
	"uploading_new_actors": "Отправка новых игроков, НИПов и питомцев",
	"waiting_for_fight_end": "Данные обработаны. Ожидание окончания сражения для последующей отправки.",
	"processed_new_fights": "Обработанные новые сражения.",
	"compressing_data": "Сжатие данных файла лога",
	"no_file_selected_error": "Вы должны указать файл.",
	"invalid_file_selected_error": "Выбран некорректный файл.",
	"file_too_large_error": "Вес файла составляет больше 1,5 гигабайт. Разделите файл лога и загрузите части по отдельности. Вы можете сделать это нажав \"Домой\", а затем \"Разделить Лог\"",
	"file_too_many_days_error": "Этот лог содержит данные за несколько дней. Вы должны или разделить его на отдельные файлы перед отправкой, или выбрать конкретные сражения для отправки.",
	"no_region_selected_error": "Для персональных логов Вы должны указать конкретный регион перед отправкой. Нажмите на кнопку <i>Выбрать...</i> выше и выберите регион.",
	"cleanup_success": "Очистка прошла успешно.",
	"cleaning_up": "Очистка...",
	"uploading_remaining": "Загрузка оставшихся данных до окончания сеанса...",
	"assuming_combat_over": "Предполагается, что бой завершен. Сжатие данных файла лога",
	"reading_new_log_data": "Чтение новых данных из файла лога",
	"no_livelog_location_error": "Вы должны указать директорию с файлом лога, который собираетесь транслировать.",
	"invalid_livelog_location_error": "Выбрана некорректная директория файла лога.",
	"confirm_deletion": "Вы уверены, что хотите удалить этот файл?",
	"yes": "Да",
	"no": "Нет",
	"deletion_failed": "Удаление не удалось. Закройте другие приложения и попробуйте снова.",
	"deletion_success": "Файл был успешно удален.",
	"confirm_archival": "Вы уверены, что хотите архивировать этот файл?",
	"archival_success": "Файл был успешно архивирован.",
	"archival_failure": "Архивирование не удалось. Закройте другие приложения и попробуйте снова.",
	"no_fight_selected": "Вы должны выбрать как минимум одно сражение для отправки.",
	"date_label": "Дата:",
	"duration_label": "Длительность:",
	"friendlies_label": "Дружественные участники:",
	"enemies_label": "Вражеские участники:",
	"wipe": "Вайп",
	"kill": "Убийство",
	"start_recording_button": "Начать запись",
	"no_directory_error": "Вы должны указать директорию.",
	"invalid_directory_error": "Выбрана некорректная директория.",
	"stop_recording_button": "Остановить запись.",
	"stop_button": "Стоп",
	"delete_button": "Удалить",
	"archive_button": "Архивировать",
	"ff_act_warning": "Для загрузки логов необходим ACT плагин версии 2.0.2.9 или выше.",
	"warcraft_difficulty_mythic": "Эпохальный",
	"warcraft_difficulty_heroic": "Героический",
	"warcraft_difficulty_flex": "Гибкий",
	"warcraft_difficulty_normal": "Обычный",
	"warcraft_difficulty_lfr": "СПР",
	"warcraft_difficulty_challenge_mode": "РИ",
	"warcraft_difficulty_mythic_plus": "Эпохальный+",
	"live_version": "Тёмные земли",
	"classic_version": "Классический",
	"test_version": "ПТР",
	"forgot_password": "Забыли пароль?",
	"create_account": "Регистрация",
	"release_notes": "Список изменений",
	"characters": "Персонажи",
	"guilds": "Гильдии",
	"reports": "Отчёты",
	"reports_viewer": "Reports Viewer",
	"character_viewer": "Characters Viewer",
	"guild_viewer": "Guilds Viewer",
	"rankings": "Рейтинги",
	"gear": "Экипировка",
	"character_viewer_desc1": "На этой панели отображается информация о персонажах. Вы можете загрузить персонажа любым из следующих способов:",
	"character_viewer_desc2": "Введите имя персонажа в поле поиска выше.",
	"character_viewer_desc3": "Выберите одного из ваших персонажей на боковой панели <i>Мои Гильдии</i>.",
	"character_viewer_desc4": "Щелкните на имя персонажа на боковой панели <i>Последние Персонажи</i>.",
	"raids": "Рейд",
	"mythic_plus_dungeons": "Эпохальные+ подземелья",
	"my_characters": "Мои персонажи",
	"my_guilds": "Мои Гильдии",
	"recent_characters": "Recent Characters",
	"group_applicants": "Group Applicants",
	"recent_reports": "Recent Reports",
	"edit": "Редактировать",
	"show_hide_overlay": "Показать/Скрыть оверлей",
	"call_wipe": "Call a Wipe: ",
	"call_wipe_help": "Pressing the <em>Call a Wipe</em> hotkey while live-logging will allow you to filter the uploaded fight to only the data that was recorded before a wipe was called.",
	"calling_wipe": "Calling a wipe...",
	"wipe_called": "A wipe has been called.",
	"failed_to_call_wipe": "Failed to call a wipe.",
	"can_only_call_a_wipe_when_live_logging": "You can only call a wipe if you are live logging.",
	"guild_viewer_desc1": "This pane shows information about guilds. You can load a guild using any of the following methods:",
	"guild_viewer_desc2": "Type a guild name into the search field above.",
	"guild_viewer_desc3": "Select one of your guilds from the <i>My Guilds</i> sidebar.",
	"operation_in_progress": "An operation is already in progress and must complete before you can continue.",
	"character_lookup_uses_preferred_region": "Character lookup uses your preferred region."
}
 
module.exports = { ru }